//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_tm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresses
    {
        public long id { get; set; }
        public int indeks { get; set; }
        public long region_id { get; set; }
        public long city_id { get; set; }
        public long street_id { get; set; }
    }
}
