//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_tm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public long id { get; set; }
        public long partner_type_id { get; set; }
        public long partner_id { get; set; }
        public long director_id { get; set; }
        public string partner_email { get; set; }
        public string partner_phone { get; set; }
        public long partner_adress_id { get; set; }
        public long INN { get; set; }
        public int rating { get; set; }
    }
}
