//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_tm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public long id { get; set; }
        public int product_type_id { get; set; }
        public string product_name { get; set; }
        public int article { get; set; }
        public decimal minimal_price_for_partner { get; set; }
    }
}
