//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_tm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public long id { get; set; }
        public string product_type { get; set; }
        public decimal coef_product_type { get; set; }
    }
}
